### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by toshiro-koba** [toshiro-koba/furima-29725#10]
# URL
https://furima-29725.herokuapp.com/

# Basic認証用データ
## ID
admin
## パスワード
2222

# 出品者用データ
## ニックネーム
test_user1
## メールアドレス
test@1
## パスワード
aaaaa1

# 購入者用データ
## ニックネーム
test_user2
## メールアドレス
test@2
## パスワード
aaaaa2

# 購入用カードデータ
## 番号
4242424242424242
## 期限
12/24
## セキュリティコード
123

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。

**Comment by toshiro-koba** [comment]
ご確認いただきありがとうございました！！
